// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJ8b_4XGYEMgUD8oTLmWl7QtF2jVx5Jc',
    appId: '1:870569556593:web:41549185b74040b79439d0',
    messagingSenderId: '870569556593',
    projectId: 'caspian-dfd9a',
    authDomain: 'caspian-dfd9a.firebaseapp.com',
    storageBucket: 'caspian-dfd9a.firebasestorage.app',
    measurementId: 'G-WHHPEQ5RKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8GNX88C5JkQD_7zJ3mrdHqtM6RJsdqUs',
    appId: '1:870569556593:android:e1391c6864acf6959439d0',
    messagingSenderId: '870569556593',
    projectId: 'caspian-dfd9a',
    storageBucket: 'caspian-dfd9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwm_WkS7h0zQkIs_Qy_9si_TpDK85_h4',
    appId: '1:870569556593:ios:946b61d07184b0719439d0',
    messagingSenderId: '870569556593',
    projectId: 'caspian-dfd9a',
    storageBucket: 'caspian-dfd9a.firebasestorage.app',
    androidClientId: '870569556593-i8cr97hennf3h3umtkmrkn258b9585do.apps.googleusercontent.com',
    iosClientId: '870569556593-0uhmt0gn8iap4q1mr1li76jump4e5etj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}